amcsplatform/amcsrestapi

swaggerpay/payswaggerlatest.json

updating Swagger

---

swaggerpay/payswaggerlatest.json

Updating AMCSPay Server URL to https://eu1-pay-dev.amcsplatform.com for Client to test.

Update Server URL

---

swaggerpay/payswaggerlatest.json

User story 369655 - Create Swagger Documentation for Refunds

External transactions - Refunds Swagger Documentation

---

swaggerpay/payswaggerlatest.json

Updating Swagger Contract
Issue with CallerTransactionId and CallerIPAddress
Fix descriptions and added it
Fixed formatting

Update Swagger Contract

---

swaggerpay/payswaggerlatest.json

Issue is with Required tag which is not handled properly in the response

Update Poll Payment API Contract

---

swaggerpay/payswaggerlatest.json

Update swagger documentation for POST /ExternalTransaction/Terminal

User Story 352009: AMCS Pay: Update Swagger Documentation for POST /Terminalpayment Restful API for Verifone

---

swaggerpay/payswaggerlatest.json

Updated Terminal payment documentation, removed token expiry.

Removed token expiry

---

swaggerpay/payswaggerlatest.json

Updating required fields for Vault Payments

---

swaggerpay/payswaggerlatest.json

US 369657, implement SWAGGER Doc for DeleteToken endpoint

User Story 369657: AMCS Pay: Create Swagger Documentation for POST Delete Token Restful AMCS Pay API

---

swaggerpay/payswaggerlatest.json

Pushing changes on behalf of Steven due to access constraint. :)
…GET API to get transaction status

User Story 369682: AMCS Pay: Create Swagger Documentation for AptPay GET API to get transaction status

---

swaggerpay/payswaggerlatest.json

Pushing changes on behalf of Steven due to access constraint. :)

US 369674 - add examples

---

swaggerpay/payswaggerlatest.json

Updates for US 369681, 369674, 369674.
Committing changes on behalf of Steven and Boris.

Updates for US 369681, 369674, 369674-

---

swaggerpay/payswaggerlatest.json

Commit changes from Boris for AptPay Add Disbursement.

update for add disbursement

---

index.html
swaggerpay/payswaggerlatest.json

Updates for Add Identity description format. - From Steven

Updates for Add Identity description format.

---

swaggerpay/payswaggerlatest.json

Updated Add Identity Requests and Transaction Status Response

Updated Add Identity Requests and Transaction Status Response

---

index.html
swaggerpay/payswaggerlatest.json

Commit index update for custom style on description and AddDisbursement Update

Commit index update for custom style on description

---

swaggerpay/payswaggerlatest.json

Add RequestType to Terminal and TerminalAbort API

Add RequestType to Terminal and TerminalAbort API

---

swaggerpay/payswaggerlatest.json

Add Request Id to Poll Request if Terminal does not receive back the response.

Add RequestId to Poll Request

---

swaggerpay/payswaggerlatest.json

Add TerminalPay to Refund

---

swaggerpay/payswaggerlatest.json

- Updated AddDisbursement's request and response object
- Remove AddIdentity and replace with AddSupplier
**Add Supplier**
**Add Disbursement**

update AddDisbursement and AddSupplier

---

swaggerpay/payswaggerlatest.json

**Code Changes:**
1. Add EftCanada in provider type for vault tansaction 
2. Remove duplicate item in AMCSPayTerminalAbortRequest > required array
**Dev Testing:**

User Story 463125: EFTCanada / Trux Integration - External APIs for processing vault payments (Vault / AutoPay)

---

swaggerpay/payswaggerlatest.json

Added /disbursement/GetSupplier endpoint

User Story 369677: AMCS Pay: Create Swagger Documentation for AptPay GETbyid API to fetch supplier details

---

swaggerpay/payswaggerlatest.json

Add EFTCanada enum to all provider type

---

swaggerpay/payswaggerlatest.json

Added Check Account in the Swagger Doc

User Story 369685: AMCS Pay: Create Swagger Documentation for AptPay POST API to check if a card is eligible to receive funds

---

swaggerpay/payswaggerlatest.json

Change Logs:
1. remove 404
2. add required to required params
3. add optional to optional params

369685 - QA Requests

---

swaggerpay/payswaggerlatest.json

Add GetIdentity Endpoint

---

swaggervisionai/visionaiswaggerlatest.json

VisionAI API doc - Add description section

489375 visionai external api doc - add description section

---

swaggerpay/payswaggerlatest.json

adding service fee tag

---

swaggerpay/payswaggerlatest.json

fixing abort response contract and poll response description

fixing abort response contract and poll response description

---

swaggerpay/payswaggerlatest.json

Adding changes as requested by trux

adding a fix for trux issue

---

swaggerpay/payswaggerlatest.json

Token not required for ACH AND ACI

added fix for Swagger Trux issue

---

swaggererp/erpswaggerlatest.json

Update swagger erp documentation

Update swagger erp documentation

---

swaggererp/erpswaggerlatest.json

Added account balance endpoints:
/accounting/accountBalances/{guid}
/accounting/accountBalances

Added account balance endpoint

---

swaggerpay/payswaggerlatest.json

Update swagger documentation to EFTCanada to APG and ImmediateOneOff

User Story 668867: Update Swagger documentation for Immediate One-Off Payment (IVR)

---

swaggerpay/payswaggerlatest.json

User Story 668867: Update Swagger documentation for Immediate One-Off Payment (IVR)-additional change
